# Generated by Django 4.2.5 on 2023-09-22 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='ctg')),
            ],
        ),
        migrations.CreateModel(
            name='TgUser',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('ism', models.CharField(max_length=128, null=True)),
                ('familiya', models.CharField(max_length=128, null=True)),
                ('username', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=128)),
                ('lang', models.CharField(default='uz', max_length=2)),
                ('log', models.JSONField(default={'state': 0})),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('img', models.ImageField(upload_to='product')),
                ('price', models.IntegerField()),
                ('tarkibi', models.TextField()),
                ('ctg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.category')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('quent', models.IntegerField(default=1)),
                ('summ', models.IntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.product')),
            ],
        ),
    ]
